name: My first Github Workflow
on: [push]
jobs:
  Setter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencis
      run:
        python -m pip install --upgrade pip
        pip install pylint pylint-exit conan
    - name: Analysing the code with pylint
      run:
        pylint $(git ls-files app.py)
  myFirst-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Python version
        run:
          python3 --version
      - name: docker version
        run:
          docker --version
  Test-pylint:
    runs-on: ubuntu-latest
    steps:    
      - name: pylint
        run: 
          pylint app.py
  BuildApp:
    runs-on: ubuntu-latest
    steps:    
      - name: docker build
        run:
          docker build --tag test-flask-app .
