name: My first Github Workflow
on: [push]
jobs:
  myFirst-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Python version
        run:
          python3 --version
      - name: docker version
        run:
          docker --version
  Test-pylint:
    runs-on: ubuntu-latest
    steps:    
      - name: pylint
        run: 
          pylint app.py
  BuildApp:
    runs-on: ubuntu-latest
    steps:    
      - name: docker build
        run:
          docker build --tag test-flask-app .
